export const FACILITIES_SEED = [
  {
    name: 'Спортплекс "Динамо"',
    sport: 'Футбол',
    city: 'Москва',
    district: 'Центр',
    address: 'ул. Ленина, 15',
    pricePerHour: 1500,
    description:
      'Современный спортивный комплекс с профессиональным стадионом и трибунами. Идеален для футбола, тренировок и турниров.',
    openTime: '08:00',
    closeTime: '23:00',
    photos: [],
    reviews: [
      { author: 'Иван', rating: 5, text: 'Отличное место! Чистая площадка' },
      { author: 'Мария', rating: 4, text: 'Хорошо, но дороговато' },
      { author: 'Петр', rating: 5, text: 'Супер! Рекомендую всем' },
    ],
  },
  {
    name: 'Теннис Клуб "Волк"',
    sport: 'Теннис',
    city: 'Москва',
    district: 'ЮААО',
    address: 'ул. Пушкина, 30',
    pricePerHour: 2000,
    description: 'Профессиональный теннисный клуб с 4 кортами, тренерами и раздевалками.',
    openTime: '09:00',
    closeTime: '22:00',
    photos: [],
    reviews: [
      { author: 'Алексей', rating: 5, text: 'Шикарные корты!' },
      { author: 'Елена', rating: 4, text: 'Всё нравится, но дорого' },
    ],
  },
  {
    name: 'Баскетбольный зал "Чемпион"',
    sport: 'Баскетбол',
    city: 'Москва',
    district: 'СВАО',
    address: 'проспект Комсомольский, 12',
    pricePerHour: 1200,
    description: 'Современный баскетбольный зал с профессиональным паркетом. Раздевалки и душевые.',
    openTime: '07:00',
    closeTime: '23:00',
    photos: [],
    reviews: [
      { author: 'Максим', rating: 4, text: 'Хороший паркет' },
      { author: 'Данила', rating: 4, text: 'Всё чётко' },
    ],
  },
  {
    name: 'Волейбольный центр "Сеточка"',
    sport: 'Волейбол',
    city: 'Москва',
    district: 'ЗАО',
    address: 'ул. Минская, 45',
    pricePerHour: 1800,
    description: 'Просторный волейбольный центр с несколькими площадками.',
    openTime: '10:00',
    closeTime: '22:00',
    photos: [],
    reviews: [{ author: 'Татьяна', rating: 5, text: 'Отличное место для тренировок!' }],
  },
  {
    name: 'Бадминтонный клуб "Волан"',
    sport: 'Бадминтон',
    city: 'Москва',
    district: 'Центр',
    address: 'ул. Тверская, 20',
    pricePerHour: 900,
    description: 'Уютный бадминтонный клуб с 3 площадками.',
    openTime: '09:00',
    closeTime: '21:00',
    photos: [],
    reviews: [{ author: 'Виталий', rating: 4, text: 'Чистенько, уютно' }],
  },
  {
    name: 'Спортзал им. Кутузова',
    sport: 'Баскетбол',
    city: 'Москва',
    district: 'ЮВАО',
    address: 'ул. Академика Костычева, 5',
    pricePerHour: 1000,
    description: 'Классический спортивный зал. Надёжное место для тренировок.',
    openTime: '06:00',
    closeTime: '22:00',
    photos: [],
    reviews: [{ author: 'Сергей', rating: 4, text: 'Немного старое, но функционально' }],
  },
  {
    name: 'Теннисный центр СПб',
    sport: 'Теннис',
    city: 'Санкт-Петербург',
    district: 'Центр',
    address: 'Невский проспект, 100',
    pricePerHour: 2200,
    description: 'Премиальный теннисный центр в центре Санкт-Петербурга. 8 кортов.',
    openTime: '08:00',
    closeTime: '23:00',
    photos: [],
    reviews: [{ author: 'Ирина', rating: 5, text: 'Премиум уровень!' }],
  },
  {
    name: 'Футбольная база "Позитив"',
    sport: 'Футбол',
    city: 'Казань',
    district: 'Вахитовский',
    address: 'ул. Баумана, 50',
    pricePerHour: 1300,
    description: 'Спортивная база с естественным и искусственным покрытием.',
    openTime: '09:00',
    closeTime: '20:00',
    photos: [],
    reviews: [{ author: 'Булат', rating: 4, text: 'Хорошая база' }],
  },
  {
    name: 'Хоккейный дворец "Лёд"',
    sport: 'Хоккей',
    city: 'Москва',
    district: 'САО',
    address: 'ул. Мира, 88',
    pricePerHour: 3500,
    description: 'Профессиональный хоккейный дворец с ледяной ареной.',
    openTime: '08:00',
    closeTime: '23:00',
    photos: [],
    reviews: [
      { author: 'Павел', rating: 5, text: 'Отличная ледяная арена' },
      { author: 'Денис', rating: 5, text: 'Супер площадка!' },
    ],
  },
  {
    name: 'Сквош центр "Ракетка"',
    sport: 'Сквош',
    city: 'Москва',
    district: 'СЗАО',
    address: 'ул. Октябрьская, 22',
    pricePerHour: 1600,
    description: 'Современный сквош центр с 5 кортами.',
    openTime: '09:00',
    closeTime: '21:00',
    photos: [],
    reviews: [{ author: 'Олег', rating: 5, text: 'Отличные корты' }],
  },
  {
    name: 'Клуб настольного тенниса "Пинг-Понг"',
    sport: 'Настольный теннис',
    city: 'Москва',
    district: 'ВАО',
    address: 'пр. Косыгина, 3',
    pricePerHour: 700,
    description: 'Любительский клуб с 8 столами.',
    openTime: '10:00',
    closeTime: '22:00',
    photos: [],
    reviews: [{ author: 'Иван', rating: 4, text: 'Хороший клуб' }],
  },
  {
    name: 'Волейбол Клуб СПб "Волна"',
    sport: 'Волейбол',
    city: 'Санкт-Петербург',
    district: 'Петроградский',
    address: 'Петроградская ул., 15',
    pricePerHour: 1700,
    description: 'Волейбольный клуб в историческом центре. Две площадки.',
    openTime: '09:00',
    closeTime: '21:00',
    photos: [],
    reviews: [{ author: 'Ирина', rating: 5, text: 'Отличные условия' }],
  },
];
